export class TestLogger {
  // Helper to generate a standardized ISO timestamp
//   private static getTimestamp(): string {
//     return new Date().toISOString();
//   }

  // Info level for general steps
  static info(message: string): void {
    console.log(`INFO: ${message}`);
  }

  // Success level for passed assertions or operations
  static success(message: string): void {
    console.log(`SUCCESS: ${message}`);
  }

  // Output level for printing dynamic runtime data (like autogenerated emails)
  static output(label: string, value: string): void {
    console.log(`OUTPUT: ${label} -> ${value}`);
  }

  // Error level for failures
  static error(message: string, errorDetails?: any): void {
    console.error(`ERROR: ${message}`, errorDetails || '');
  }
}